name: health_plus
description: Revision Of healthplus

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_search_bar: ^2.1.0
  bubble: ^1.1.9+1
  analog_clock: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  http: ^0.12.2
  image_picker: ^0.6.7+14


dev_dependencies:
  flutter_test:
    sdk: flutter
  syncfusion_flutter_calendar: ^18.3.42


flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Light.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Light.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700

